### ISSUE TITLE
error on invoking helm-swoop

### ISSUE THREAD

**Issue by jack99999** [ShingoFukuyama/helm-swoop#10]
when i M-x helm-swoop  and the cursor is on text, i get the following:
Wrong type argument: stringp, nil

if i put the cursor on a blank line then it works ok.

the problem is not related to the file type... a new buffer that is not associated with a file shows the same problem.

jack

**Comment by zackp30** [comment]
Also getting the same issue, I don't have `ac-helm` installed at all.
