### ISSUE TITLE
helm swoop is extremely slow in a buffer of 30000 lines

### ISSUE THREAD

**Issue by amosbird** [ShingoFukuyama/helm-swoop#120]
Is there a way to improve the speed?

**Comment by ShingoFukuyama** [comment]
There is no easy way to handle such a big file on Emacs. I usually edit massive files on VSCode.

**Comment by ShingoFukuyama** [comment]
VSCode "Large file support"  https://code.visualstudio.com/updates/v1_15#_large-file-support

**Comment by ShingoFukuyama** [comment]
This setting might help a little.

```lisp
;;If nil, you can slightly boost invoke speed in exchange for text color
(setq helm-swoop-speed-or-color nil)
```
