### ISSUE TITLE
Is it possible to clear the helm-swoop cache manually?

### ISSUE THREAD

**Issue by krizex** [ShingoFukuyama/helm-swoop#127]
As we know, helm-swoop will cache the search result until modifies the buffer. However sometime I don't modify the buffer but just switch the git branch, so that content of the buffer has changed, and I get the incorrect search result by using helm-swoop. Is it possible to clear the cache manually?

**Comment by CeleritasCelery** [comment]
eval `(helm-swoop--clear-cache)`

**Comment by krizex** [comment]
Thanks @CeleritasCelery !
