### ISSUE TITLE
Is it possible to have helm-swoop same syntax highlighting? 

### ISSUE THREAD

**Issue by ReneFroger** [ShingoFukuyama/helm-swoop#37]
Hi Shingo!

Thanks for sharing this plugin! Reminds me much of Unite Line. 

One question. Is it possible to have same syntax highlighting in the helm swoop window of the file, like in the buffer? 

For example, 

`If (test)` in the buffer, the `if` have the color red, the `test` have default color. 

In helm swoop window, `if` and `test` have same default colors. 

Maybe enable it as an option?

Thanks in advance for your reply.

**Comment by tuhdo** [comment]
Yes, you can. It is disabled by default, and you need to set it to `t`:

```elisp
;; If nil, you can slightly boost invoke speed in exchange for text color
(setq helm-swoop-speed-or-color t)
```

**Comment by ReneFroger** [comment]
Amazing, tuhdo. I find it surprisingly that you replied on every Helm-related issue, and I honestly appreciate it. 
I gave myself some weeks to configure and bend Emacs to my taste, and explore his power. I rally enjoyed your tutorials about Emacs and Helm. Thanks for that! I asked a little question on the Helm tutorial on your page, by the way. 

This issue can be closed now, thanks to @tuhdo.

**Comment by tuhdo** [comment]
Thanks to Github's notification :)

Btw, I already answered my question on my page.
