### ISSUE TITLE
HOWTO: call helm-swoop within another function for searching a fixed-regexp.

### ISSUE THREAD

**Issue by shankarpdy** [ShingoFukuyama/helm-swoop#38]
This is not a issue. It is a query of how to do things.
I want to write a function, which calls helm-swoop with a fixed regexp in the current buffer only.

Something like:
(defun search-keys ()
   (interactive)
   (helm-swoop "^//[ ]\*")
)

From the documentation, it looks like this. But not sure how to use this.
(helm-swoop &key $QUERY $SOURCE ($MULTILINE current-prefix-arg))

**Comment by ShingoFukuyama** [comment]
Does it work?

```
(defun search-keys ()
  (interactive)
  (helm-swoop :$query "^[0-9]+\\s-\\/\\/[\\ ]*")
  )
// ^[0-9]+ :: helm-swoop's regexp match includes line numbers
// \\s- or [\\ ] :: space match
```

**Comment by shankarpdy** [comment]
This works extremely nice.
One minor correction in the regexp.
[\\\\ ] :: space match -> in order for me to get [\\ ] in the swoop command-line.
