### ISSUE TITLE
Enable fuzzy-matching for Helm Swoop

### ISSUE THREAD

**Issue by tuhdo** [ShingoFukuyama/helm-swoop#42]
Helm has its built-in fuzzy searcher and can be enabled with `:fuzzy-match t` per helm source. I wish to have an option to enable fuzzy searching with Helm Swoop. Is it ok if you add this feature?

**Comment by PythonNut** [comment]
+1

**Comment by ReneFroger** [comment]
+1 And the option to turn off case sensitive, would be great too.

**Comment by Devagamster** [comment]
+1

**Comment by ShingoFukuyama** [comment]
Added :)

**Comment by ReneFroger** [comment]
Is this enabled by default, or you need to configure Swoop manually to enable the fuzzy searching?

**Comment by ReneFroger** [comment]
Is there any way to disable the fuzzy matching for helm-swoop? The results are unusable for me at this moment.

**Comment by ShingoFukuyama** [comment]
If you do not prefer the fuzzy matching, you can disable it like below:

```
(setq helm-c-source-swoop-match-functions
  '(helm-mm-exact-match
    helm-mm-match
    ;;helm-fuzzy-match
    ;;helm-mm-3-migemo-match
    ))
(setq helm-c-source-swoop-search-functions
      '(helm-mm-exact-search
        helm-mm-search
        helm-candidates-in-buffer-search-default-fn
        ;;helm-fuzzy-search
        ;;helm-mm-3-migemo-search
        ))
```

**Comment by ReneFroger** [comment]
Thanks for your reply. It worked now again in the usual way. I like the fuzzy flx feature for `helm-for-files`. but with Helm Swoop I search on specific keywords. Thanks for your reply.
