### ISSUE TITLE
Consistent isearch-mode C-s behaviour while in helm-swoop

### ISSUE THREAD

**Issue by priyadarshan** [ShingoFukuyama/helm-swoop#43]
Hi,

It would be very nice to have `C-s` behaviour consistent to `isearch-mode`,  at least as an option.

I.e., while `helm-swoop` is active, pressing `C-s` would move to next search result. Other keys would also be nice (see http://www.emacswiki.org/emacs/IncrementalSearch#toc2), even just `C-s` would be a wonderful addition.

Thanks for considering this, and thank you for the wonderful `helm-swoop`.

**Comment by priyadarshan** [comment]
Sorry, only now I see #26. Thanks for that. Feel free to close this ticket.

**Comment by ShingoFukuyama** [comment]
It would be better to write it on document... Thank you :)
