### ISSUE TITLE
Text is read only?

### ISSUE THREAD

**Issue by ReneFroger** [ShingoFukuyama/helm-swoop#47]
I run `M-x eshell`. 

Then I would like to filter the contents of buffer. When I start `M-x helm-swoop`, I get the message `Text is read-only`. But I don't get it why Helm Swoop cannot filter the buffer contents? 

I looked into the documentation, but without sufficient information. Could you tell more about it? 

Thanks in advance!

**Comment by ShingoFukuyama** [comment]
I guess your setting has:
`(setq helm-swoop-speed-or-color t)`

It seems like helm-swoop gets color with read-only property.
Could you set the variable nil for the present?

**Comment by ReneFroger** [comment]
Indeed, `(setq helm-swoop-speed-or-color nil)` does the trick. Thanks for your suggestion. 

Is there a way to 'swoop' read-only files? Because the colors in Helm Swoop helps me to distinct the structure of file.

**Comment by ShingoFukuyama** [comment]
I've fixed it at the latest version, so it take a few hours to be reflected on MELPA.
Thanks!

**Comment by ReneFroger** [comment]
Thanks! I appreciate it!
