### ISSUE TITLE
Reference to free variable `helm-swoop-last-prefix-number' warning

### ISSUE THREAD

**Issue by corvideon** [ShingoFukuyama/helm-swoop#50]
Hi

I am using GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) on a Mac.
I have Helm Swoop 1.4 installed. When I start Emacs I get a Compile-Log buffer with the following warning:

.emacs.d/elpa/helm-swoop-1.4/helm-swoop.elc:Warning: reference to free
    variable `helm-swoop-last-prefix-number'

I have looked through the code and the variable seems to be defined, so I am puzzled at the warning.
This is not a major issue obviously, but perhaps you can see what the problem might be.

Many thanks

Seamus

**Comment by ShingoFukuyama** [comment]
Thank you for reporting.
I think the error has gone away.
If the error persists, please reopen this issue :)
