### ISSUE TITLE
ad-Advice-select-window: Wrong type argument: window-live-p, #<window 94>

### ISSUE THREAD

**Issue by ryanartecona** [ShingoFukuyama/helm-swoop#53]
Emacs newbie here. I can enter start helm-swoop and go into edit mode, but neither <kbd>C-x C-s</kbd> nor <kbd>C-c C-g</kbd> work to get me out of it. The error I'm seeing is in the issue title: 

    ad-Advice-select-window: Wrong type argument: window-live-p, #<window 94>

I'm using [Spacemacs](https://github.com/syl20bnr/spacemacs), so there are lots of minor modes that could be confusing things here (including Evil and its supporting minor modes). I'm not sure how to go about digging into the issue to see what's causing it, but happy to help with some guidance :)

This is currently keeping me from using helm-swoop, which makes me sad.

**Comment by ryanartecona** [comment]
This was broken for me for a while, but just started working again. It still happens intermittently, but no longer blocks helm-swoop usage.

Feel free to close if low priority!

**Comment by ShingoFukuyama** [comment]
Thank you for reporting.

I guess the error occur when `select-window` function called but the target window is already removed...
Could you try `M-x help-for-help`, and type `f` key, then input `ad-Advice-select-window` in the mini buffer.
`*Help*` buffer would appear with relevant functions in it. What does the buffer content say?

**Comment by ryanartecona** [comment]
Here's the contents of `describe-function` for `ad-Advice-select-window`:

    ad-Advice-select-window is a compiled Lisp function.

    (ad-Advice-select-window AD--ADDOIT-FUNCTION WINDOW &optional
    NORECORD)

    After-advice `powerline-select-window':
    makes powerline aware of window changes

    After-advice `evil'.

    [back]

**Comment by ShingoFukuyama** [comment]
I thought the error is attributed to either `powerline` or `evil`.
But I couldn't reproduce the error, so please let me know when you find any clue.

**Comment by ryanartecona** [comment]
Yeah, probably. Either way, this has happened less (none?) for me recently, and even if it resurfaces I'm not yet experienced enough in Emacs to trace the problem to its source. I'll close this and reopen if I ever hit this issue again and find any more clues. :mag:
