### ISSUE TITLE
helm-match-plugin-mode no longer exists in helm

### ISSUE THREAD

**Issue by plantarum** [ShingoFukuyama/helm-swoop#55]
helm has removed `helm-match-plugin-mode`:

https://github.com/emacs-helm/helm/commit/865fa2718534b4177d0165fc37817ac43eb9f010

This minor mode and related symbols are still referenced in `helm-swoop`:

https://github.com/ShingoFukuyama/helm-swoop/blob/f67fa8a4fe3b968b7105f8264a96da61c948a6fd/helm-swoop.el#L611

which breaks it in the current version.

**Comment by WorldsEndless** [comment]
Is this why I'm getting the error, 
    	helm-swoop--restore: Symbol's value as variable is void: helm-swoop-pattern

right after I discovered this great plugin?

**Comment by jcpetkovich** [comment]
No, I believe that's unrelated. I think that probably has to do with some outdated bytecompiled lisp on your system, can you try the following:

    C-0 M-x byte-recompile-directory RET ~/.emacs.d/elpa RET

Or so.

This should get you looking at the same error this bug report refers to, which you can also solve temporarily by deleting the conditionals that use `helm-match-plugin-mode` in `helm-swoop.el` and byte recompiling again.

**Comment by plantarum** [comment]
I'm not very familiar with helm or helm-swoop, but the initial problem I had was getting the same error reported by @WorldsEndless above:

 > Symbol's value as variable is void: helm-swoop-pattern

Which showed up as soon as I called `helm-swoop`. I fixed that temporarily with 

    (setq helm-swoop-pattern "")

After that, calling `helm-swoop` produced:

 > Symbol's value as variable is void: helm-match-plugin-mode

I followed that as far as the issue I reported above. I just recompiled `~/.emacs.d/elpa` as suggested by @jcpetkovich and ran `emacs -Q`, and the problems persist.

I can't say if the problems are actually related, but I don't think it's just a byte-compilation issue :/

**Comment by plantarum** [comment]
UPDATE: commenting out the conditionals, as suggested by @jcpetkovich apparently fixed both problems. Can't say if that's just dumb luck, or if they were in fact related issues.

**Comment by jcpetkovich** [comment]
@plantarum, sorry, yes I should have been a little clearer about that maybe.

Unfortunately, removing `helm-match-plugin-mode` seems to have removed the highlighting from helm-swoop within the helm buffer. Not sure what's causing that.

**Comment by WorldsEndless** [comment]
Thanks, @plantarum . I'm working again.

**Comment by kaushalmodi** [comment]
I also see this problem.

**Comment by ShingoFukuyama** [comment]
Thank you everyone :)
Now the problem solved without losing highlighting.
