### ISSUE TITLE
Source buffer position doesn't account for narrowing when moving between candidates

### ISSUE THREAD

**Issue by vermiculus** [ShingoFukuyama/helm-swoop#67]
1. Insert a large amount of text (line-wise) into a buffer and narrow it to an arbitrary section.
2. Execute `helm-swoop` and enter query text.
3. Note source buffer does not agree with candidate selection buffer as different candidates are selected.

This is likely caused by a simple `goto-line` somewhere. I'll bet there is some version of `goto-line` that takes buffer narrowing into account, but I haven't the freedom to poke around that today :smile:

**Comment by vermiculus** [comment]
As a matter of fact, behavior is completely erratic when the buffer has undergone narrowing. If I widen the buffer after swooping, only the narrowed text will be searched. Is there some sort of caching going on?

**Comment by ShingoFukuyama** [comment]
Thank you for the issue, I also had been bothered by the behavior once in a while.
As you mentioned, buffer caching is the culprit, but I managed to clear cache by narrowing or widening :grinning:
