### ISSUE TITLE
Swoop freezes emacs with large files and long lines

### ISSUE THREAD

**Issue by etergo** [ShingoFukuyama/helm-swoop#79]
When editing a large latex file (50,000 words), with long lines (paragraphs wrapped by visual line mode) helm swoop freezes emacs requiring a forced quit. This is probably beyond the normal use-case but I find it incredibly useful to use.

**Comment by sandos** [comment]
I just opened a file of size 33800KiB, and it did take several tens of seconds to get a reaction from swoop. Each and every new character typed produces another long delay. It does get "fast" with few or no search hits.

I suspected long lines to be the culprit, but after replacing them with empty lines in Notepad++, the file is still similarly slow. At 20MiB it is a bit better. 13 MiB is still slow. At 8MiB performance gets livable, but still not good. At 4MiB I think the performance is OK.

It doesn't feel like performance is linear with respect to file-size.

**Comment by etergo** [comment]
Okay, thanks. Does that put the difficulty beyond the scope of the plugin?

**Comment by etergo** [comment]
I have found that a completely unrelated line my .emacs was causing this bug. Closing issue.

**Comment by lufeihaidao** [comment]
Similar issue in Emacs 25.
Helm-swoop freezes emacs if I type too fast.

**Comment by zarzen** [comment]
Same issue when operating large file(1.2MB). Search function works fine, but after hit `enter`  to jump that line, emacs freezed.
