### ISSUE TITLE
Symbol's value as variable is void: $buf

### ISSUE THREAD

**Issue by vixr** [ShingoFukuyama/helm-swoop#81]
I'm consistently getting this error when I try to select one of the matches from helm-swoop in the minibuffer:

`Symbol's value as variable is void: $buf`

This is with 20150831.843 from melpa

**Comment by syohex** [comment]
See #80.

**Comment by syohex** [comment]
@vixr #80 was merged. Please check latest version and close this issue if you have no problems.
