### ISSUE TITLE
multi-line helm-swoop tries to use string-join

### ISSUE THREAD

**Issue by sandos** [ShingoFukuyama/helm-swoop#84]
I get "Symbols definition is void: string-join" when trying C-u 5 M-x helm-swoop using emacs 24.5.1 on Windows 7.

This worked just a short time ago, so its likely a new change that has broken something. Also I saw this when googling: https://github.com/remvee/android-mode/issues/6, where the commit seems to imply one should use mapconcat instead of string-join.

**Comment by syohex** [comment]
You can import `string-join` by `(require 'subr-x)`.

**Comment by syohex** [comment]
`subr-x.el` was provided since Emacs 24.4. If helm-swoop.el decide to support Emacs 24.4 or higher, this issue can be fixed by following patch.

```patch
diff --git a/helm-swoop.el b/helm-swoop.el
index ec5e4e2..06cee6d 100644
--- a/helm-swoop.el
+++ b/helm-swoop.el
@@ -7,7 +7,7 @@
 ;; URL: https://github.com/ShingoFukuyama/helm-swoop
 ;; Created: Oct 24 2013
 ;; Keywords: helm swoop inner buffer search
-;; Package-Requires: ((helm "1.0") (emacs "24"))
+;; Package-Requires: ((helm "1.0") (emacs "24.4"))
 
 ;; This program is free software; you can redistribute it and/or
 ;; modify it under the terms of the GNU General Public License as
@@ -87,6 +87,7 @@
 ;;; Code:
 
 (require 'cl-lib)
+(require 'subr-x)
 (require 'helm)
 (require 'helm-utils)
 (require 'helm-grep)
```

**Comment by ShingoFukuyama** [comment]
@sandos @syohex Thanks!
I should've use `(mapconcat 'identity '("foo" "bar" "baz") "")` for joining.
