### ISSUE TITLE
Cache is not cleared by narrow-to-defun

### ISSUE THREAD

**Issue by lexa** [ShingoFukuyama/helm-swoop#88]
Problem is that if i narrow to function, helm-swoop cache won't be cleared. 

How to reproduce problem:
1. open helm-swoop.el
2. go to line 100
3. call helm swoop : M-x helm-swoop
4. quit from helm mode : C-g
3. narrow to function : M-x narrow-to-defun
4. call helm swoop : M-x helm-swoop

Now i see matches in all lines including lines hidden by narrowing.

P.S. narrowing to region works just fine.

**Comment by ShingoFukuyama** [comment]
Thank you, I've fixed now :)
