### ISSUE TITLE
Multiline behavior doesn't work with helm-multi-swoop/helm-multi-swoop-all

### ISSUE THREAD

**Issue by elgoog** [ShingoFukuyama/helm-swoop#92]
Multiline behavior (with arguments M-[number]) doesn't work well with helm-multi-swoop and helm-multi-swoop-all. These commands show matched 1 line always in the result.
Is there any way to use multiline behavior with these commands?

**Comment by ShingoFukuyama** [comment]
Multiline behavior is different from `helm-multi-swoop`.
(I know this is a bit misleadingly named, though)

If you bind key something like `(global-set-key (kbd "M-i") 'helm-swoop)`, `M-3 M-i` or `M-10 M-i` will allow `helm-swoop' multiline function.

On the other hand, `helm-multi-swoop` targets multiple buffers with each single line.
If you open several `.html` extension files, `M-x helm-multi-swoop-all` automatically select all `.html` buffer as target buffers.

**Comment by ShingoFukuyama** [comment]
Sorry for misinterpreting. Multline behavior on `helm-multi-swoop` doesn't work.

**Comment by ShingoFukuyama** [comment]
I see it can be implemented, so I'll add multiline ability on `helm-multi-swoop` :)

**Comment by elgoog** [comment]
Thank you for your reply.
I wait for the update:+1:

**Comment by elgoog** [comment]
Thank you for the update!
I confirmed multiline behavior works with helm-multi-swoop(-all) after this update.
Closing this issue because the objective was completed.
