### ISSUE TITLE
helm-swoop-last-prefix-number: variable is void

### ISSUE THREAD

**Issue by NgaNguyenDuy** [ShingoFukuyama/helm-swoop#95]
I am using Emacs 24.4.1 on Debian 8.3. When use helm-multi-swoop-all or helm-multi-swoop and then move around buffers i got this error:

`Symbol's value as variable is void: helm-swoop-last-prefix-number`

Can anyone help me fix it?

**Comment by ShingoFukuyama** [comment]
Thanks to @NgaNguyenDuy and @syohex, the error is fixed.

**Comment by pcompassion** [comment]
Can I get updated package in melpa?

**Comment by syohex** [comment]
Yes you can if you use MELPA repository, not MELPA stable repository.
